Add BucketNotification.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,6 +22,15 @@ on:
 
 jobs:
   deploy:
+    - name: Delete broken stack if needed
+    run: |
+      STATUS=$(aws cloudformation describe-stacks --stack-name my-stack-name --query "Stacks[0].StackStatus" --output text || echo "NOT_FOUND")
+      if [ "$STATUS" = "ROLLBACK_COMPLETE" ]; then
+        echo "Deleting failed stack..."
+        aws cloudformation delete-stack --stack-name my-stack-name
+        aws cloudformation wait stack-delete-complete --stack-name my-stack-name
+      fi
+
     name: Deploy stack to AWS
     runs-on: ubuntu-latest
     outputs:
